=== DAM1-COTARELO-25-26/proyecto-web-jari/datos/animes.dtd
<!ELEMENT catalogoAnimes (anime+)>
<!ATTLIST catalogoAnimes
    fechaRegistro CDATA #REQUIRED
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>

<!ELEMENT anime (titulo, sinopsis, fechaPublicacion, fechaFin?, destacado, rating, generos, temporadas, personajes)>
<!ATTLIST anime
    id ID #REQUIRED
    estado (emision | finalizado | cancelado) #REQUIRED
    tipo (TV | Movie | OVA) #REQUIRED
>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ELEMENT fechaFin (#PCDATA)>
<!ELEMENT destacado (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

<!ELEMENT generos (genero+)>
<!ELEMENT genero (#PCDATA)>

<!ELEMENT temporadas (temporada+)>
<!ATTLIST temporadas
    total CDATA #REQUIRED
>

<!ELEMENT temporada (episodios, fechaEstreno)>
<!ATTLIST temporada
    numero CDATA #REQUIRED
>

<!ELEMENT episodios (#PCDATA)>
<!ELEMENT fechaEstreno (#PCDATA)>

<!ELEMENT personajes (principales, secundarios, villanos)>
<!ELEMENT principales (protagonista+)>
<!ELEMENT secundarios (coprotagonista+)>
<!ELEMENT villanos (antagonista+)>

<!ELEMENT protagonista (#PCDATA)>
<!ELEMENT coprotagonista (#PCDATA)>
<!ELEMENT antagonista (#PCDATA)>

=== DAM1-COTARELO-25-26/proyecto-web-jari/datos/animes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/anime-to-html.xsl"?>
<!DOCTYPE catalogoAnimes SYSTEM "animes.dtd">
<catalogoAnimes 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="animes.xsd"
    fechaRegistro="2026-02-13">

    <anime id="A001" estado="finalizado" tipo="TV">
        <titulo>Naruto</titulo>
        <sinopsis>Naruto Uzumaki es un niño marginado en la aldea de Konoha que alberga en su interior al Zorro de Nueve Colas. Su sueño es convertirse en Hokage, el líder de la aldea, para ganar el respeto de todos. A través de exámenes ninja y misiones peligrosas, descubre el valor de la amistad y el trabajo duro.</sinopsis>
        <fechaPublicacion>2002-10-03</fechaPublicacion>
        <fechaFin>2007-02-08</fechaFin>
        <destacado>true</destacado>
        <rating>8.3</rating>
        <generos>
            <genero>Acción</genero>
            <genero>Aventura</genero>
            <genero>Shonen</genero>
        </generos>
        <temporadas total="5">
            <temporada numero="1">
                <episodios>57</episodios>
                <fechaEstreno>2002-10-03</fechaEstreno>
            </temporada>
            <temporada numero="2">
                <episodios>43</episodios>
                <fechaEstreno>2003-11-05</fechaEstreno>
            </temporada>
            <temporada numero="3">
                <episodios>41</episodios>
                <fechaEstreno>2004-09-08</fechaEstreno>
            </temporada>
            <temporada numero="4">
                <episodios>42</episodios>
                <fechaEstreno>2005-07-06</fechaEstreno>
            </temporada>
            <temporada numero="5">
                <episodios>37</episodios>
                <fechaEstreno>2006-05-03</fechaEstreno>
            </temporada>
        </temporadas>
        <personajes>
            <principales>
                <protagonista>Naruto Uzumaki</protagonista>
            </principales>
            <secundarios>
                <coprotagonista>Sasuke Uchiha</coprotagonista>
                <coprotagonista>Sakura Haruno</coprotagonista>
                <coprotagonista>Kakashi Hatake</coprotagonista>
            </secundarios>
            <villanos>
                <antagonista>Orochimaru</antagonista>
                <antagonista>Itachi Uchiha</antagonista>
                <antagonista>Gaara</antagonista>
            </villanos>
        </personajes>
    </anime>

    <anime id="A002" estado="finalizado" tipo="TV">
        <titulo>Assassination Classroom</titulo>
        <sinopsis>Una misteriosa criatura con tentáculos destruye la luna y amenaza con hacer lo mismo con la Tierra. Sin embargo, ofrece una oportunidad: se convierte en el profesor de la clase 3-E, donde los estudiantes deben intentar asesinarlo antes de la graduación para salvar el mundo y ganar una recompensa.</sinopsis>
        <fechaPublicacion>2015-01-10</fechaPublicacion>
        <fechaFin>2016-06-20</fechaFin>
        <destacado>false</destacado>
        <rating>8.0</rating>
        <generos>
            <genero>Comedia</genero>
            <genero>Acción</genero>
            <genero>Escolar</genero>
        </generos>
        <temporadas total="2">
            <temporada numero="1">
                <episodios>22</episodios>
                <fechaEstreno>2015-01-10</fechaEstreno>
            </temporada>
            <temporada numero="2">
                <episodios>25</episodios>
                <fechaEstreno>2016-01-07</fechaEstreno>
            </temporada>
        </temporadas>
        <personajes>
            <principales>
                <protagonista>Koro-sensei</protagonista>
                <protagonista>Nagisa Shiota</protagonista>
            </principales>
            <secundarios>
                <coprotagonista>Karma Akabane</coprotagonista>
                <coprotagonista>Kaede Kayano</coprotagonista>
                <coprotagonista>Tadaomi Karasuma</coprotagonista>
            </secundarios>
            <villanos>
                <antagonista>Gakuho Asano</antagonista>
                <antagonista>Shiro</antagonista>
                <antagonista>Akira Takaoka</antagonista>
            </villanos>
        </personajes>
    </anime>

    <anime id="A003" estado="finalizado" tipo="TV">
        <titulo>Attack on Titan</titulo>
        <sinopsis>Tras ver a su madre ser devorada por un titán, Eren Yeager jura eliminar a todos los gigantes de la faz de la tierra. Se une al Cuerpo de Exploración, la élite militar que lucha fuera de los muros, descubriendo oscuros secretos sobre el origen de los titanes y la historia de la humanidad.</sinopsis>
        <fechaPublicacion>2013-04-07</fechaPublicacion>
        <fechaFin>2023-11-05</fechaFin>
        <destacado>true</destacado>
        <rating>9.1</rating>
        <generos>
            <genero>Acción</genero>
            <genero>Drama</genero>
            <genero>Fantasía</genero>
        </generos>
        <temporadas total="4">
            <temporada numero="1">
                <episodios>25</episodios>
                <fechaEstreno>2013-04-07</fechaEstreno>
            </temporada>
            <temporada numero="2">
                <episodios>12</episodios>
                <fechaEstreno>2017-04-01</fechaEstreno>
            </temporada>
            <temporada numero="3">
                <episodios>22</episodios>
                <fechaEstreno>2018-07-23</fechaEstreno>
            </temporada>
            <temporada numero="4">
                <episodios>35</episodios>
                <fechaEstreno>2020-12-07</fechaEstreno>
            </temporada>
        </temporadas>
        <personajes>
            <principales>
                <protagonista>Eren Yeager</protagonista>
            </principales>
            <secundarios>
                <coprotagonista>Mikasa Ackerman</coprotagonista>
                <coprotagonista>Armin Arlert</coprotagonista>
                <coprotagonista>Levi Ackerman</coprotagonista>
            </secundarios>
            <villanos>
                <antagonista>Reiner Braun</antagonista>
                <antagonista>Bertholdt Hoover</antagonista>
                <antagonista>Zeke Yeager</antagonista>
            </villanos>
        </personajes>
    </anime>

    <anime id="A004" estado="emision" tipo="TV">
        <titulo>Demon Slayer</titulo>
        <sinopsis>Tanjiro Kamado regresa a casa para encontrar a su familia masacrada por un demonio. Su única superviviente, su hermana Nezuko, se ha transformado en uno. Tanjiro se convierte en cazador de demonios para encontrar una cura y vengar a su familia, enfrentándose a las Doce Lunas Demoníacas.</sinopsis>
        <fechaPublicacion>2019-04-06</fechaPublicacion>
        <destacado>true</destacado>
        <rating>8.7</rating>
        <generos>
            <genero>Acción</genero>
            <genero>Sobrenatural</genero>
        </generos>
        <temporadas total="4">
            <temporada numero="1">
                <episodios>26</episodios>
                <fechaEstreno>2019-04-06</fechaEstreno>
            </temporada>
            <temporada numero="2">
                <episodios>18</episodios>
                <fechaEstreno>2021-10-10</fechaEstreno>
            </temporada>
            <temporada numero="3">
                <episodios>11</episodios>
                <fechaEstreno>2023-04-09</fechaEstreno>
            </temporada>
            <temporada numero="4">
                <episodios>8</episodios>
                <fechaEstreno>2024-05-12</fechaEstreno>
            </temporada>
        </temporadas>
        <personajes>
            <principales>
                <protagonista>Tanjiro Kamado</protagonista>
                <protagonista>Nezuko Kamado</protagonista>
            </principales>
            <secundarios>
                <coprotagonista>Zenitsu Agatsuma</coprotagonista>
                <coprotagonista>Inosuke Hashibira</coprotagonista>
                <coprotagonista>Giyu Tomioka</coprotagonista>
            </secundarios>
            <villanos>
                <antagonista>Muzan Kibutsuji</antagonista>
                <antagonista>Akaza</antagonista>
                <antagonista>Doma</antagonista>
            </villanos>
        </personajes>
    </anime>

    <anime id="A005" estado="finalizado" tipo="TV">
        <titulo>Seven Deadly Sins</titulo>
        <sinopsis>La princesa Elizabeth busca a los Siete Pecados Capitales, un grupo de antiguos caballeros acusados de traición, para que la ayuden a salvar el reino de los Caballeros Sagrados que han dado un golpe de estado. Liderados por Meliodas, luchan contra demonios y revelan su pasado.</sinopsis>
        <fechaPublicacion>2014-10-05</fechaPublicacion>
        <fechaFin>2021-06-23</fechaFin>
        <destacado>false</destacado>
        <rating>7.9</rating>
        <generos>
            <genero>Fantasía</genero>
            <genero>Aventura</genero>
        </generos>
        <temporadas total="4">
            <temporada numero="1">
                <episodios>24</episodios>
                <fechaEstreno>2014-10-05</fechaEstreno>
            </temporada>
            <temporada numero="2">
                <episodios>24</episodios>
                <fechaEstreno>2018-01-13</fechaEstreno>
            </temporada>
            <temporada numero="3">
                <episodios>24</episodios>
                <fechaEstreno>2019-10-09</fechaEstreno>
            </temporada>
            <temporada numero="4">
                <episodios>24</episodios>
                <fechaEstreno>2021-01-13</fechaEstreno>
            </temporada>
        </temporadas>
        <personajes>
            <principales>
                <protagonista>Meliodas</protagonista>
                <protagonista>Elizabeth Liones</protagonista>
            </principales>
            <secundarios>
                <coprotagonista>Ban</coprotagonista>
                <coprotagonista>King</coprotagonista>
